services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database.sql #
  server:
    build: 
      context: .
      dockerfile: apache.Dockerfile
    ports:
      - "80:80"
