services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    image: application
    ports:
      - 80:80
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
          ports:
      - 3306:3306
