services:
  app:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    image: application
    ports:
      - 80:80
      - 433:433
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database.sql
